#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend edcodes.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 54135-web-01 34.224.6.230:80
        server 54135-web-02 54.237.224.188:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
